In [1]:
import os
import keras

/Users/gunnvantsaini/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


### Pre trained models:
1. From keras you can access them using applications module
2. The first time when you access these models, keras will download them on your machine and since these models can be fairly large, it will take some time for you to use these models the first time.
3. You will need to pre-process images in a particular manner when you use a particular model, keras makes it easy for you to do this, by using preprocess_input

### Step 1: Loading the model in the memory (if doing this for first time the model will download in the system and then loaded in the memory

In [2]:
from keras.applications.vgg16 import VGG16,preprocess_input
from keras.preprocessing.image import load_img,img_to_array
import numpy as np

In [3]:
model=VGG16()

In [ ]:
model.summary()

### Step 2: Load the image, make sure that the image is of size which the model can take as an input
https://keras.io/applications/#vgg16

In [4]:
img_path="/Users/gunnvantsaini/Documents/Work/Machine Learning Course/Python/Module 5 Neural Networks/Codes/pizza.jpg"
img=load_img(img_path,target_size=(224,224))

In [5]:
img.size

(224, 224)

### Step 3 : Preprocess the data, image must be converted to an array and then necessary pre-processing be applied

In [6]:
img_array=img_to_array(img)

In [7]:
img_array.shape

(224, 224, 3)

In [8]:
img_array=np.expand_dims(img_array,axis=0)

In [9]:
img_array.shape

(1, 224, 224, 3)

In [10]:
img_array

array([[[[242., 242., 244.],
         [240., 241., 243.],
         [233., 234., 236.],
         ...,
         [173., 163., 161.],
         [172., 162., 161.],
         [172., 162., 161.]],

        [[225., 226., 230.],
         [234., 235., 237.],
         [248., 248., 250.],
         ...,
         [174., 164., 163.],
         [170., 160., 159.],
         [170., 160., 159.]],

        [[237., 238., 240.],
         [253., 253., 253.],
         [255., 255., 255.],
         ...,
         [171., 161., 160.],
         [172., 162., 161.],
         [171., 161., 160.]],

        ...,

        [[136., 126., 117.],
         [138., 129., 120.],
         [138., 129., 122.],
         ...,
         [124., 111.,  92.],
         [122., 110.,  88.],
         [124., 111.,  92.]],

        [[137., 124., 116.],
         [135., 124., 118.],
         [137., 128., 121.],
         ...,
         [124., 111.,  92.],
         [123., 110.,  91.],
         [122., 109.,  90.]],

        [[138., 125., 116.],
       

In [11]:
img_pre_processed=preprocess_input(img_array)

In [12]:
img_pre_processed

array([[[[140.061    , 125.221    , 118.32     ],
         [139.061    , 124.221    , 116.32     ],
         [132.061    , 117.221    , 109.32     ],
         ...,
         [ 57.060997 ,  46.221    ,  49.32     ],
         [ 57.060997 ,  45.221    ,  48.32     ],
         [ 57.060997 ,  45.221    ,  48.32     ]],

        [[126.061    , 109.221    , 101.32     ],
         [133.061    , 118.221    , 110.32     ],
         [146.061    , 131.22101  , 124.32     ],
         ...,
         [ 59.060997 ,  47.221    ,  50.32     ],
         [ 55.060997 ,  43.221    ,  46.32     ],
         [ 55.060997 ,  43.221    ,  46.32     ]],

        [[136.061    , 121.221    , 113.32     ],
         [149.061    , 136.22101  , 129.32     ],
         [151.061    , 138.22101  , 131.32     ],
         ...,
         [ 56.060997 ,  44.221    ,  47.32     ],
         [ 57.060997 ,  45.221    ,  48.32     ],
         [ 56.060997 ,  44.221    ,  47.32     ]],

        ...,

        [[ 13.060997 ,   9.221001 ,  1

### Step 4: Use the pre-processed array to obtain predictions from the model

In [13]:
from keras.applications.vgg16 import decode_predictions

In [14]:
preds=model.predict(img_pre_processed)

In [15]:
preds

array([[8.09405321e-12, 1.19740040e-09, 3.63045878e-11, 6.16768095e-12,
        5.38119896e-12, 4.67018257e-10, 1.60714237e-11, 6.41267942e-11,
        6.68801792e-10, 2.15077760e-12, 3.10412651e-09, 3.94311334e-10,
        2.09437645e-09, 1.35691194e-10, 8.78269419e-12, 1.84269364e-10,
        1.54407667e-11, 2.10021878e-11, 1.06973232e-11, 6.47694398e-11,
        5.73020190e-12, 5.49855474e-12, 1.32985615e-12, 1.92453128e-12,
        1.05192504e-11, 4.44279752e-11, 1.43763085e-10, 8.15150947e-10,
        1.81952335e-11, 6.80917545e-11, 7.43054299e-11, 1.61425220e-10,
        1.58936564e-09, 4.55192412e-10, 3.86958209e-11, 1.22815829e-11,
        1.36552381e-10, 3.92725352e-10, 4.79941586e-10, 6.89640359e-12,
        1.59172814e-10, 7.92500527e-12, 1.62174815e-10, 1.45306519e-11,
        1.93776297e-11, 6.91387156e-11, 1.28756367e-10, 1.16889542e-09,
        9.66811050e-13, 2.53121257e-11, 1.08658291e-10, 1.90061664e-11,
        1.60220018e-10, 3.37314815e-10, 5.36554667e-09, 8.574716

In [16]:
decode_predictions(preds,top=5)

[[('n07873807', 'pizza', 0.9987103),
  ('n07693725', 'bagel', 0.00047675657),
  ('n07717410', 'acorn_squash', 0.00014626133),
  ('n07716358', 'zucchini', 0.00013352944),
  ('n07753113', 'fig', 0.00010797983)]]

### vgg16 model is trained on imagenet database to identify 1000 common objects/animals/places etc

In [17]:
decode_predictions(preds,top=1000)

[[('n07873807', 'pizza', 0.9987103),
  ('n07693725', 'bagel', 0.00047675657),
  ('n07717410', 'acorn_squash', 0.00014626133),
  ('n07716358', 'zucchini', 0.00013352944),
  ('n07753113', 'fig', 0.00010797983),
  ('n07684084', 'French_loaf', 9.5818395e-05),
  ('n07768694', 'pomegranate', 9.028094e-05),
  ('n07875152', 'potpie', 5.453906e-05),
  ('n07579787', 'plate', 3.535247e-05),
  ('n02776631', 'bakery', 3.1126794e-05),
  ('n07742313', 'Granny_Smith', 1.4971447e-05),
  ('n07745940', 'strawberry', 1.3797816e-05),
  ('n04263257', 'soup_bowl', 9.127831e-06),
  ('n07747607', 'orange', 7.679436e-06),
  ('n03400231', 'frying_pan', 6.849958e-06),
  ('n07871810', 'meat_loaf', 5.9920667e-06),
  ('n07860988', 'dough', 5.3712897e-06),
  ('n04270147', 'spatula', 4.8429533e-06),
  ('n07720875', 'bell_pepper', 3.9306487e-06),
  ('n04597913', 'wooden_spoon', 3.5990254e-06),
  ('n07697537', 'hotdog', 3.5826974e-06),
  ('n07734744', 'mushroom', 3.554359e-06),
  ('n07714990', 'broccoli', 3.5347427e-06)